# GitHub Star Manager配置文件

# 基本配置
update_interval: 1    # 更新频率（天）
max_stars: 1000      # 最大获取的Star项目数量（全量模式时使用）
incremental_update: true  # 是否使用增量更新模式（只获取最新的Star项目）
incremental_max_stars: 100  # 增量更新时最大获取数量
max_items_per_doc: 50    # 每个分类文档最大项目数

# 网络请求配置
request_timeout: 30    # 请求超时时间（秒）
max_retries: 3         # 最大重试次数
retry_delay: 5         # 初始重试延迟（秒）

# AI配置
ai_model: "@cf/openai/gpt-oss-20b"  # 使用的AI模型


# 分类配置
categories:
  - 前端开发
  - 后端开发
  - 机器学习
  - 数据科学
  - 开发工具
  - 网络安全
  - 云计算
  - 桌面应用
  - 移动应用
  - 系统工具
  - 学习资源
  - 其他