# GitHub Star Manager配置文件

# 基本配置
update_interval: 7    # 更新频率（天）
max_stars: 50        # 最大获取的Star项目数量
incremental_update: true  # 是否使用增量更新模式（只获取最新的Star项目）

# 网络请求配置
request_timeout: 30    # 请求超时时间（秒）
max_retries: 3         # 最大重试次数
retry_delay: 5         # 初始重试延迟（秒）

# AI配置
ai_model: "glm-4.5-flash"  # 使用的AI模型
ai_api_url: "https://open.bigmodel.cn/api/paas/v4/chat/completions"  # AI API地址

# 分类配置
categories:
  - 前端开发
  - 后端开发
  - 机器学习
  - 数据科学
  - 开发工具
  - 系统工具
  - 学习资源
  - 其他